### ISSUE TITLE
counter-intuitive bearing function

### ISSUE THREAD

**Issue by yreecht** [nielshintzen/vmstools#13]
Hi Niels,

I was trying to calculate turn angles using VMStools and I noticed a rather counter-intuitive behaviour of the `bearing` function (code to illustrate my point below): lonRef/latRef refer to point 1 in the documentation, but if you take point 1 and 2 in their chronological order you get a direction of your point 1 looking backward from point 2 (red arrows in the example below), which is confusing! 
This kind of makes sense according to most definitions of the bearing (notably as the compass direction of a distant point). But the bearing is somewhat ambiguous and is also sometimes referring to the direction to which the vessel is pointing (which, I believe, is actually the heading). And in the context of VMStool I would intuitively think that this is its meaning, why the confusion.

So my suggestion would be to add, if possible, a wrapper function of `bearing` (could be called `heading`… I chose `vesselCourse` in the example below as this is based on actual positions, should therefore be a course) that gives an estimate of the vessel course using the positions in chronological order (blue arrows in the example).

Kind regards,
Yves

```r
library(vmstools)

## Sample of data:
lat <- c(53.63125, 53.62593, 53.62003, 53.61626, 53.61683, 53.61750)
lon <- c(-6.17412, -6.17330, -6.17629, -6.17105, -6.17068, -6.17085)
speed <- c(4.04, 4.12, 2.22, 0.22, 0.46, 0.24)

## Bearing, the intuitive way after the documentation:
?bearing
bearingAngle <- bearing(lon = tail(lon, -1), lat = tail(lat, -1),
                        lonRef = head(lon, -1), latRef = head(lat, -1))

## Plotting the positions and direction/speed vectors:
plot(lon, lat,
     pch = 16,
     asp = lonLatRatio(mean(lon), mean(lat)),
     cex = 0.8)

text(x = lon, y = lat,
     labels = as.character(1:length(lat)), adj = -0.8)

scale <- 1e-3
arrows(x0 = tail(lon, -1),
       y0 = tail(lat, -1),
       x1 = tail(lon, -1) + sin(bearingAngle * pi / 180) * head(speed, -1) * scale,
       y1 = tail(lat, -1) + cos(bearingAngle * pi / 180) * head(speed, -1) * scale,
       length = 0.07, col = "red")

## Calculating a course instead:
vesselCourse <- function(lon1, lat1, lon2, lat2)
{
    ## Purpose: Wrapper function bearing -> ~ course.
    ## ----------------------------------------------------------------------
    ## Arguments: longitudes (lon1, lon2) and latitudes (lat1, lat2)
    ##            of vessel positions 1 and 2 (in chronological order).
    ## ----------------------------------------------------------------------
    ## Author: Yves Reecht, Date:  2 Nov 2017, 08:20

    return(bearing(lon = lon1, lat = lat1, lonRef = lon2, latRef = lat2))
}

courseAngle <- vesselCourse(lon1 = head(lon, -1), lat1 = head(lat, -1),
                            lon2 = tail(lon, -1), lat2 = tail(lat, -1))

arrows(x0 = head(lon, -1),
       y0 = head(lat, -1),
       x1 = head(lon, -1) + sin(courseAngle * pi / 180) * head(speed, -1) * scale,
       y1 = head(lat, -1) + cos(courseAngle * pi / 180) * head(speed, -1) * scale,
       length = 0.07, col = "blue")
```

**Comment by nielshintzen** [comment]
Updated the documentation to make it intuitive
