### ISSUE TITLE
Effort using only TACSAT

### ISSUE THREAD

**Issue by emantzo** [nielshintzen/vmstools#14]
Thanks for your exciting lib!
I have only VMS data in the tacsat format (plus gear information by vessel). Is it possible to use track cutting/ interpolation to get the Fishing trips by vessel?
My aim is to estimate effort by gear type, quarter and area.

Thank you!!

Eirini

**Comment by nielshintzen** [comment]
There is a function named 'interpolateTacsat' to perform interpolation of VMS data. Effort can be estimated from VMS directly 
with the 'effort'. With the 'labellingHauls' you can identify hauls within a trip.
