### ISSUE TITLE
Fishing trips across two years

### ISSUE THREAD

**Issue by jepol77** [nielshintzen/vmstools#19]
The tacsat and the eflalo is divided into years, which means that if a fishing trip is for example starting the 30th of december and ending 3rd of January, it will only be able to split these among tacsat pings from one of the years.

**Comment by nielshintzen** [comment]
Include in upgrade of SplitAmongPings issue

**Comment by nielshintzen** [comment]
Added warning in splitAmongPings if trips cross the year
