### ISSUE TITLE
Upgrade code with roxygen style to improve helpfiles generation

### ISSUE THREAD

**Issue by nielshintzen** [nielshintzen/vmstools#22]
Right now, all the code in VMStools has separate manual files. Having manual pages is crucial for the package but it's tedious to maintain. As such, it's suggested to change the style of coding to roxygen to auto-generate help files and only having to write code in one place

**Comment by iagomosqueira** [comment]
I have used this in the past to get a first converted version

<https://github.com/yihui/Rd2roxygen>

**Comment by nielshintzen** [comment]
Updated to Roxygen documentation
