### ISSUE TITLE
Daylight Savings Time

### ISSUE THREAD

**Issue by neilcampbelll** [nielshintzen/vmstools#26]
Don't know if this has been an issue for others, but I have had issues with trips that cross the daylight savings time changeover. 

Could just be an issue with data cleaning, but would be helpful to flag changes to TZ within a data set and/or have some handling built in.

(simplest solution to this problem would be to abolish DST! )

**Comment by nielshintzen** [comment]
Write functionality to check for GMT vs DST-notation and how this is handled

**Comment by nielshintzen** [comment]
VMS always comes with a GMT and a local time stamp. The GMT won't be affected by daylight saving time changeovers. the format function on POSIXct strings (as we have in tacsat) will convert this correctly to local time
