### ISSUE TITLE
name convention for eflalo / tacsat 

### ISSUE THREAD

**Issue by roimartins** [nielshintzen/vmstools#27]
writing capitol mnames in R Variables slow down the processes . IS it really necessary have capitol names? 

review the naming convention as an overall

**Comment by nielshintzen** [comment]
I tested it and perhaps if you do 10^10 number of calculations this starts to matter. 
The readability though of the code greatly improves when using upper-case letters. The alternative is to use _ but who wants to rewrite so much code?
