### ISSUE TITLE
Rule based metier definition

### ISSUE THREAD

**Issue by nielshintzen** [nielshintzen/vmstools#34]
Including acceptable lists of metiers by RCGs and RDBES and conversion to Benthis metiers

**Comment by nielshintzen** [comment]
Being updated from WGSFD look-up table hosted at ICES

**Comment by colinpmillar** [comment]
I would be interested in looking into how we would link this to the WGSFD table which is accessible via a webservice.  Some options are:
* release a version of vmstools everytime wgsfd updates the lookup
* make a function that updates the package data so the user has the most up-to-date version of the lookup.
* provide example code of how to use the most up-to-date lookup

**Comment by nielshintzen** [comment]
To make sure vmstools remains relevant and up-to-date I find the use of example code most promising. This code is already available at the sfd github page
