### ISSUE TITLE
effort function - level not in function argument

### ISSUE THREAD

**Issue by einarhjorleifsson** [nielshintzen/vmstools#8]
in the `effort` function "level" is not in the function argument but is used in the code (when on passes tacsat kind of object). hence the code in Practical3 were `effort` is used breaks down:

```
tacsatp <- effort(tacsatp, level = "trip", unit = "hours",fill.na = T)
Error in effort(tacsatp, level = "trip", unit = "hours", fill.na = T) : 
  unused argument (level = "trip")
```

if one specifies in the working environment  "level" and then passes the the following specs to the function it does not cause error. mind you, still working out if this makes sense, but that is another matter :-)

```
level <- "trip"
tacsatp <- effort(tacsatp, unit = "hours",fill.na = T)
```

regards,
einar

**Comment by einarhjorleifsson** [comment]
on related thing: in the wiki Practical3 were `effort` is first introduced i am wandering if the code should not have 'by = "byRow"' rather than just using the default ("FT_REF")??

```
level <- "trip"
tacsatp <- effort(tacsatp, "byRow", unit = "hours",fill.na = T)
plotTools(subset(tacsatp,LE_GEAR == "TBB" & year(SI_DATIM) == 1801),
          level = "gridcell", xlim = c(-5,10), ylim = c(48,62), zlim = NULL, 
          log = F, gridcell = c(0.1,0.05), color = NULL,
          control.tacsat = list(clm = "EFFORT"))


eflalop <- effort(eflalo, "byRow", unit = "hours", fill.na = T)
plotTools(subset(eflalop,LE_GEAR == "TBB" & year(SI_DATIM) == 1801),
          level = "ICESrectangle", xlim = c(-5,10), ylim = c(48,62), zlim = NULL,
          log = F,color = NULL,
          control.eflalo=list(clm="EFFORT"))
```

regards, 
einar

**Comment by nielshintzen** [comment]
Practical 3 is outdated as the function has been updated recently (time is too limited to keep everything up to date, although we try). Please refer to the help file of effort for correct use.

Level should not be in the function call as it is used as a fixed setting.

Niels

**Comment by nielshintzen** [comment]
That may be a personal thing, I don’t think byRow makes a lot of sense, as that is easier calculated by intervalTacsat or for eflalo one has to watch multiple catch dates in one trip.

Niels

**Comment by einarhjorleifsson** [comment]
you are probably right.

actually i am using the vmstool inbuild data sets (tacsat, eflalao, europa, ...) to test code where the whole process is programmed via the tidyverse (dplyr, tidyr, lubridate, ... -packages). this being because it seems to me that a lot of the "specific problems" when it comes to tacsat and eflalo type of data, quite some portion seems to have a "generic solution" within "tidyverse"-functions

regards, einar
